server:
  port: 8085

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        naming:
          physical-startegy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost